"""list-orgs -- discover DSL course and cohort orgs dynamically from GitHub.

Source of truth: every org's `.github` repo is tagged by `bootstrap_course.py` -
`dsl-course-hub` for a persistent COURSE org, `dsl-cohort` for a per-year COHORT
org. This tool searches for both topics across all repos the caller can see, reads
each org's `.github/dsl-course.yml`, and emits a JSON / Markdown / YAML inventory
of the two tiers separately.

Usage:
    python3 -m dsl_course.list_orgs                       # JSON to stdout
    python3 -m dsl_course.list_orgs --format markdown     # Markdown tables
    python3 -m dsl_course.list_orgs --format yaml         # YAML
    python3 -m dsl_course.list_orgs --update-file PATH    # write the full MD page
"""

from __future__ import annotations

import argparse
import json
import sys

from .utils import gh, gh_json, log_err

COURSE_HUB_TOPIC = "dsl-course-hub"
COHORT_TOPIC = "dsl-cohort"

# The full inventory page. Entirely generated - hand edits are overwritten on the next
# refresh, so layout/prose changes belong HERE, not in the .md.
PAGE = """\
# Bootstrapped Orgs - Live Inventory

> Auto-generated by the `refresh-inventory` workflow - do not hand-edit.

## Course orgs

{course_table}

## Cohort orgs

{cohort_table}

## Regenerate on demand

> _Discovery is GitHub itself: `bootstrap_course.py` tags each org's `.github` repo:_
> - _`{course_topic}` = course org_
> - _`{cohort_topic}` = cohort org_
> - _a cohort's course org is its `dsl-course.yml` `course:` pointer._

To regenerate:

```bash
python3 -m dsl_course.list_orgs --update-file bootstrapped-orgs-inventory.md
```

Or run **Refresh Course Orgs Inventory** from the Actions tab.
"""


def _tagged_orgs(topic: str) -> list[str]:
    """Owner logins of every `.github` repo carrying `topic`."""
    results = gh_json(
        "search",
        "repos",
        f"topic:{topic}",
        "--limit",
        "100",
        "--json",
        "name,owner",
    )

    owners = []
    for repo in results:
        if repo.get("name") != ".github":
            continue
        owner = (repo.get("owner") or {}).get("login", "")
        if owner:
            owners.append(owner)
    return owners


def discover_course_orgs() -> list[dict]:
    """Find every `.github` repo tagged `dsl-course-hub` and fetch its metadata.

    Returns a list of dicts with keys: org, org_name, course_name, course_code, url.
    Sorted by org name.
    """
    orgs = []
    for owner in _tagged_orgs(COURSE_HUB_TOPIC):
        meta = _fetch_metadata(owner)
        if meta.get("course"):
            # A cohort org's dsl-course.yml is a pointer back to its course org
            # (`course:`/`org:` keys only). Cohorts bootstrapped before the topic split
            # still carry dsl-course-hub on their .github, so filter them here too -
            # this inventory enumerates COURSE orgs, never their per-year cohorts.
            continue
        orgs.append(
            {
                "org": owner,
                "org_name": meta.get("org_name", owner),
                "course_name": meta.get("course_name", ""),
                "course_code": meta.get("course_code", ""),
                "url": f"https://github.com/{owner}",
            }
        )

    orgs.sort(key=lambda o: o["org"].lower())
    return orgs


def discover_cohort_orgs() -> list[dict]:
    """Find every `.github` repo tagged `dsl-cohort` and read its course pointer.

    Returns a list of dicts with keys: org, course, url - sorted by course org, then
    cohort, so the table groups each course's deliveries together.
    """
    cohorts = [
        {
            "org": owner,
            # `or ""` also covers a bare `course:` key parsed as YAML null.
            "course": _fetch_metadata(owner).get("course") or "",
            "url": f"https://github.com/{owner}",
        }
        for owner in _tagged_orgs(COHORT_TOPIC)
    ]
    cohorts.sort(key=lambda c: (c["course"].lower(), c["org"].lower()))
    return cohorts


def _fetch_metadata(org: str) -> dict:
    """Read and parse `.github/dsl-course.yml` for an org. Returns {} on any failure."""
    code, raw = gh(
        "api",
        f"repos/{org}/.github/contents/dsl-course.yml",
        "--jq",
        ".content | @base64d",
    )
    if code != 0 or not raw:
        return {}

    try:
        import yaml

        parsed = yaml.safe_load(raw) or {}
        return parsed if isinstance(parsed, dict) else {}
    except Exception as e:
        log_err(f"could not parse dsl-course.yml for {org}: {e}")
        return {}


def render_markdown_table(orgs: list[dict]) -> str:
    """Render the course-orgs table."""
    lines = [
        "| Org | Course | Code |",
        "| --- | --- | --- |",
    ]
    for o in orgs:
        link = f"[{o['org']}]({o['url']})"
        lines.append(
            f"| {link} | {o['course_name'] or '-'} | {o['course_code'] or '-'} |"
        )
    return "\n".join(lines)


def render_cohort_table(cohorts: list[dict]) -> str:
    """Render the cohort-orgs table."""
    lines = [
        "| Cohort org | Course org |",
        "| --- | --- |",
    ]
    for c in cohorts:
        link = f"[{c['org']}]({c['url']})"
        course = (
            f"[{c['course']}](https://github.com/{c['course']})"
            if c["course"]
            else "_(orphaned)_"
        )
        lines.append(f"| {link} | {course} |")
    return "\n".join(lines)


def render_page(orgs: list[dict], cohorts: list[dict]) -> str:
    """The complete inventory page - PAGE with both tables filled in."""
    return PAGE.format(
        course_table=render_markdown_table(orgs),
        cohort_table=render_cohort_table(cohorts),
        course_topic=COURSE_HUB_TOPIC,
        cohort_topic=COHORT_TOPIC,
    )


def update_file(path: str, page: str) -> bool:
    """Write the fully generated page to `path`. Returns True if the file changed."""
    from pathlib import Path

    p = Path(path)
    if p.exists() and p.read_text() == page:
        return False

    p.write_text(page)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--format",
        choices=["json", "markdown", "yaml"],
        default="json",
        help="Output format when writing to stdout. Default: json.",
    )
    parser.add_argument(
        "--update-file",
        default=None,
        help="Markdown file to (over)write with the fully generated inventory page.",
    )
    args = parser.parse_args()

    orgs = discover_course_orgs()
    cohorts = discover_cohort_orgs()

    if args.update_file:
        changed = update_file(args.update_file, render_page(orgs, cohorts))
        print(
            f"{'updated' if changed else 'no change'}: {args.update_file} "
            f"({len(orgs)} course orgs, {len(cohorts)} cohort orgs)"
        )
        return 0

    combined = {"course_orgs": orgs, "cohort_orgs": cohorts}
    if args.format == "json":
        print(json.dumps(combined, indent=2))
    elif args.format == "yaml":
        import yaml

        print(yaml.safe_dump(combined, sort_keys=False))
    else:
        print(render_markdown_table(orgs))
        print()
        print(render_cohort_table(cohorts))

    return 0


if __name__ == "__main__":
    sys.exit(main())
